import { InterviewTopic } from "./types";

export const interviewTopics: InterviewTopic[] = [
  {
    id: "playwright-js-ts",
    name: "Playwright with JavaScript/TypeScript",
    icon: "TestTube",
    description: "Modern end-to-end testing with Playwright using JavaScript or TypeScript",
    questionCount: 35,
    difficulty: "medium",
    categories: ["Playwright", "E2E Testing", "JavaScript", "TypeScript", "Automation"],
  },
  {
    id: "cypress",
    name: "Cypress Testing",
    icon: "TestTube",
    description: "End-to-end testing with Cypress framework",
    questionCount: 30,
    difficulty: "medium",
    categories: ["Cypress", "E2E Testing", "JavaScript", "Automation", "CI/CD"],
  },
  {
    id: "selenium-java",
    name: "Selenium with Java",
    icon: "TestTube",
    description: "Web automation testing using Selenium WebDriver with Java",
    questionCount: 40,
    difficulty: "medium",
    categories: ["Selenium", "Java", "WebDriver", "TestNG", "Maven"],
  },
  {
    id: "selenium-python",
    name: "Selenium with Python",
    icon: "TestTube",
    description: "Web automation testing using Selenium WebDriver with Python",
    questionCount: 38,
    difficulty: "medium",
    categories: ["Selenium", "Python", "WebDriver", "Pytest", "Automation"],
  },
  {
    id: "qa-combined",
    name: "QA Automation - Combined",
    icon: "TestTubes",
    description: "Comprehensive QA automation covering multiple frameworks and tools",
    questionCount: 50,
    difficulty: "hard",
    categories: ["Selenium", "Playwright", "Cypress", "Best Practices", "Frameworks"],
  },
  {
    id: "api-testing",
    name: "API Testing",
    icon: "Network",
    description: "REST API testing with Postman, REST Assured, and automation tools",
    questionCount: 35,
    difficulty: "medium",
    categories: ["REST API", "Postman", "REST Assured", "JSON", "Authentication"],
  },
  {
    id: "performance-testing",
    name: "Performance Testing",
    icon: "Gauge",
    description: "Load testing, stress testing, and performance optimization",
    questionCount: 30,
    difficulty: "hard",
    categories: ["JMeter", "K6", "Load Testing", "Metrics", "Optimization"],
  },
  {
    id: "frontend",
    name: "Frontend Development",
    icon: "Monitor",
    description: "React, JavaScript, CSS, HTML, and modern frontend frameworks",
    questionCount: 45,
    difficulty: "medium",
    categories: ["React", "JavaScript", "CSS", "TypeScript", "Performance"],
  },
  {
    id: "backend",
    name: "Backend Development",
    icon: "Server",
    description: "Node.js, APIs, databases, and server-side architecture",
    questionCount: 40,
    difficulty: "medium",
    categories: ["Node.js", "REST APIs", "Databases", "Authentication", "Microservices"],
  },
  {
    id: "system-design",
    name: "System Design",
    icon: "Network",
    description: "Scalable architecture, distributed systems, and design patterns",
    questionCount: 30,
    difficulty: "hard",
    categories: ["Scalability", "Load Balancing", "Caching", "Database Design", "CDN"],
  },
  {
    id: "behavioral",
    name: "Behavioral Interview",
    icon: "Users",
    description: "Leadership, teamwork, conflict resolution, and STAR method responses",
    questionCount: 35,
    difficulty: "easy",
    categories: ["Leadership", "Teamwork", "Problem Solving", "Communication", "Adaptability"],
  },
];


export const interviewQuestions: Record<string, string[]> = {
  "Playwright with JavaScript/TypeScript": [
    "What is Playwright and how does it differ from other testing frameworks like Selenium?",
    "Explain how to handle multiple browser contexts in Playwright.",
    "How do you handle dynamic waits and element synchronization in Playwright?",
    "What are the different locator strategies in Playwright? Which one do you prefer and why?",
    "How would you implement page object model pattern in Playwright?",
    "Explain how to handle file uploads and downloads in Playwright.",
    "How do you run Playwright tests in parallel? What are the benefits and challenges?",
    "What is auto-waiting in Playwright and how does it work?",
    "How would you handle authentication and session management in Playwright tests?",
    "Explain how to integrate Playwright tests into a CI/CD pipeline.",
  ],
  "Cypress Testing": [
    "What are the main advantages and limitations of Cypress compared to Selenium?",
    "Explain the architecture of Cypress and how it runs tests.",
    "How do you handle asynchronous operations in Cypress?",
    "What is the difference between cy.get() and cy.contains() in Cypress?",
    "How would you implement custom commands in Cypress?",
    "Explain how to handle iframes in Cypress tests.",
    "What are Cypress fixtures and how do you use them for test data management?",
    "How do you handle API testing in Cypress using cy.request()?",
    "What is the purpose of cy.intercept() and how would you use it for API mocking?",
    "How would you set up Cypress for cross-browser testing?",
  ],
  "Selenium with Java": [
    "What is Selenium WebDriver and how does it work internally?",
    "Explain the difference between findElement() and findElements() in Selenium.",
    "How do you handle dynamic elements and waits in Selenium? Explain implicit, explicit, and fluent waits.",
    "What is the Page Object Model and why is it important in test automation?",
    "How would you handle multiple windows or tabs in Selenium WebDriver?",
    "Explain how to handle alerts, pop-ups, and frames in Selenium.",
    "What is TestNG and how does it help in organizing test cases?",
    "How do you implement data-driven testing in Selenium with TestNG?",
    "What are the different types of WebDriver exceptions you've encountered and how do you handle them?",
    "How would you integrate Selenium tests with Maven and run them in Jenkins?",
  ],
  "Selenium with Python": [
    "How do you set up Selenium WebDriver with Python?",
    "Explain the difference between implicit and explicit waits in Selenium Python.",
    "What locator strategies does Selenium support? Which ones do you use most frequently?",
    "How do you handle dropdowns and select elements in Selenium Python?",
    "What is pytest and how do you use it with Selenium for test automation?",
    "How would you implement the Page Object Model pattern in Python with Selenium?",
    "Explain how to handle cookies and browser storage in Selenium Python.",
    "How do you take screenshots on test failure in Selenium Python?",
    "What is the difference between driver.close() and driver.quit()?",
    "How would you run Selenium Python tests in headless mode?",
  ],
  "QA Automation - Combined": [
    "Compare Selenium, Playwright, and Cypress. When would you choose each?",
    "What are the key principles of a good test automation framework?",
    "How do you decide what to automate and what to test manually?",
    "Explain the testing pyramid and how it applies to automation strategy.",
    "How do you handle flaky tests in your automation suite?",
    "What is continuous testing and how does it fit into CI/CD?",
    "How do you manage test data in automation frameworks?",
    "What reporting tools have you used for test automation? How do you present results to stakeholders?",
    "How would you design a hybrid automation framework?",
    "What are some best practices for maintaining test automation code?",
  ],
  "API Testing": [
    "What is the difference between REST and SOAP APIs?",
    "How do you test RESTful APIs? What are the key things to validate?",
    "Explain the different HTTP methods (GET, POST, PUT, DELETE, PATCH) and when to use each.",
    "What is REST Assured and how do you use it for API testing?",
    "How do you handle authentication in API testing (Basic Auth, Bearer Token, OAuth)?",
    "What are status codes? Explain the difference between 200, 201, 400, 401, 403, 404, and 500.",
    "How would you validate JSON response schema in API tests?",
    "What is the difference between positive and negative API testing?",
    "How do you perform API testing in Postman? Can you automate it?",
    "How would you test API performance and response times?",
  ],
  "Performance Testing": [
    "What is the difference between load testing, stress testing, and spike testing?",
    "Explain what JMeter is and how you would use it for performance testing.",
    "What are the key performance metrics you monitor during load testing?",
    "How do you identify performance bottlenecks in an application?",
    "What is think time and pacing in performance testing?",
    "How would you design a performance test scenario for an e-commerce application?",
    "What is the difference between throughput and response time?",
    "How do you correlate dynamic values in performance testing scripts?",
    "What tools have you used for performance testing besides JMeter?",
    "How do you analyze performance test results and create reports?",
  ],
  "Frontend Development": [
    "Explain the virtual DOM and how React uses it for rendering.",
    "What are React hooks? Explain useState and useEffect with examples.",
    "How would you optimize a React application experiencing performance issues?",
    "Explain the difference between controlled and uncontrolled components.",
    "What is the Context API and when would you use it over Redux?",
    "Describe CSS specificity and how the cascade works.",
    "What are Web Vitals and how do you measure them?",
    "Explain the event loop in JavaScript.",
  ],
  "Backend Development": [
    "Explain RESTful API design principles.",
    "How do you handle authentication and authorization in a Node.js application?",
    "What is the difference between SQL and NoSQL databases?",
    "Explain middleware in Express.js.",
    "How would you design a rate limiter?",
    "What are microservices and when would you use them?",
    "Explain database indexing and its impact on performance.",
    "How do you handle error handling in async Node.js code?",
  ],
  "System Design": [
    "Design a URL shortener like bit.ly.",
    "How would you design a real-time chat application?",
    "Design a social media news feed system.",
    "How would you design a distributed cache?",
    "Design a file storage service like Dropbox.",
    "How would you design a notification system?",
  ],
  "Behavioral Interview": [
    "Tell me about a time you had to deal with a difficult team member.",
    "Describe a project where you had to learn a new technology quickly.",
    "How do you handle disagreements with your manager?",
    "Tell me about a time you failed and what you learned from it.",
    "How do you prioritize tasks when everything seems urgent?",
    "Describe a situation where you went above and beyond.",
  ],
};

export const aiResponses: Record<string, string[]> = {
  good: [
    "Excellent answer! You demonstrated a strong understanding of the concept. Your explanation was clear and well-structured.",
    "Great response! You covered the key points effectively. I especially liked how you provided practical examples.",
    "Very well articulated! Your answer shows deep knowledge of the subject. The real-world context you added was valuable.",
  ],
  average: [
    "Good start, but let's dig deeper. Can you elaborate on the specific mechanisms involved?",
    "You've covered the basics well. However, consider discussing the trade-offs and edge cases.",
    "Decent answer. To strengthen it, try to include more specific examples and discuss alternative approaches.",
  ],
  poor: [
    "I think there might be some confusion here. Let me help clarify — the key concept involves...",
    "That's partially correct, but there are some important aspects missing. Let's revisit the fundamentals.",
    "I'd encourage you to think about this differently. Consider the underlying principles first.",
  ],
};

